### ISSUE TITLE
Error finding symbol level.getIslandString() on initial build.

### ISSUE THREAD

**Issue by chrisl8** [DrFair/ExampleMod#1]
When just pulling down the repository and building it as is in IntelliJ I get this error:

```
ExampleMod\src\main\java\examplemod\examples\ExampleMethodPatch.java:53: error: cannot find symbol
        System.out.println("Entered SurfaceGrassObject.getLootTable(level, x, y): " + grassObject.getStringID() + " on level " + level.getIslandString());
                                                                                                                                      ^
  symbol:   method getIslandString()
  location: variable level of type Level
```

It appears that `Level.getIslandString` does not exist in `Necesse.jar`.

If I remove this reference in both locations within the file, it build successfully.
https://github.com/DrFair/ExampleMod/blame/master/src/main/java/examplemod/examples/ExampleMethodPatch.java#L53
https://github.com/DrFair/ExampleMod/blame/master/src/main/java/examplemod/examples/ExampleMethodPatch.java#L65

Am I doing something wrong, or was `Level.getIslandString` removed from the game after this example was built?

**Comment by DrFair** [comment]
This is just because it’s made for an older version of the game. I will get to updating it at some point :)
